name: "Sneezry"
description: "I write code."
url: https://sneezry.com
author:
    name: Sneezry
    email: lizhe@lizhe.org

exclude: [README.md, Rakefile]
paginate: 5
paginate_path: "/page/:num/"
permalink: /:year/:month/:day/:title
gems: [jekyll-paginate]